import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/billigst">
          <a>Hvor er det billigst å lade?</a>
        </Link>
        <Link href="/tid">
          <a>Hvor lenge må jeg lade?</a>
        </Link>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
